// Ticker → company name, for Analyze autocomplete. Ported from the original
// app's TICKER_DB. Any symbol can still be typed; this only powers suggestions.
export const TICKERS: [string, string][] = [
  ['AAPL', "Apple"],
  ['MSFT', "Microsoft"],
  ['NVDA', "Nvidia"],
  ['GOOGL', "Alphabet"],
  ['AMZN', "Amazon"],
  ['META', "Meta"],
  ['TSLA', "Tesla"],
  ['BRK.B', "Berkshire Hathaway"],
  ['TSM', "Taiwan Semi"],
  ['AMD', "AMD"],
  ['NFLX', "Netflix"],
  ['CRM', "Salesforce"],
  ['AVGO', "Broadcom"],
  ['ORCL', "Oracle"],
  ['ADBE', "Adobe"],
  ['INTC', "Intel"],
  ['CSCO', "Cisco"],
  ['IBM', "IBM"],
  ['QCOM', "Qualcomm"],
  ['TXN', "Texas Instruments"],
  ['MU', "Micron"],
  ['AMAT', "Applied Materials"],
  ['LRCX', "Lam Research"],
  ['KLAC', "KLA Corp"],
  ['SNPS', "Synopsys"],
  ['CDNS', "Cadence"],
  ['MRVL', "Marvell"],
  ['PANW', "Palo Alto Networks"],
  ['CRWD', "CrowdStrike"],
  ['ZS', "Zscaler"],
  ['FTNT', "Fortinet"],
  ['NET', "Cloudflare"],
  ['DDOG', "Datadog"],
  ['SNOW', "Snowflake"],
  ['MDB', "MongoDB"],
  ['NOW', "ServiceNow"],
  ['INTU', "Intuit"],
  ['WDAY', "Workday"],
  ['HUBS', "HubSpot"],
  ['TTD', "Trade Desk"],
  ['ANET', "Arista Networks"],
  ['SMCI', "Super Micro"],
  ['DELL', "Dell"],
  ['HPQ', "HP"],
  ['ROKU', "Roku"],
  ['ZM', "Zoom"],
  ['DOCU', "DocuSign"],
  ['TWLO', "Twilio"],
  ['V', "Visa"],
  ['MA', "Mastercard"],
  ['PYPL', "PayPal"],
  ['SQ', "Block"],
  ['COIN', "Coinbase"],
  ['SOFI', "SoFi"],
  ['HOOD', "Robinhood"],
  ['AFRM', "Affirm"],
  ['FIS', "Fidelity National"],
  ['FISV', "Fiserv"],
  ['GPN', "Global Payments"],
  ['JPM', "JPMorgan"],
  ['BAC', "Bank of America"],
  ['GS', "Goldman Sachs"],
  ['MS', "Morgan Stanley"],
  ['C', "Citigroup"],
  ['WFC', "Wells Fargo"],
  ['SCHW', "Schwab"],
  ['BLK', "BlackRock"],
  ['AXP', "American Express"],
  ['COF', "Capital One"],
  ['USB', "U.S. Bancorp"],
  ['PNC', "PNC Financial"],
  ['TFC', "Truist"],
  ['BK', "BNY Mellon"],
  ['CME', "CME Group"],
  ['ICE', "Intercontinental Exchange"],
  ['SPGI', "S&P Global"],
  ['UNH', "UnitedHealth"],
  ['LLY', "Eli Lilly"],
  ['JNJ', "Johnson & Johnson"],
  ['MRK', "Merck"],
  ['PFE', "Pfizer"],
  ['ABBV', "AbbVie"],
  ['TMO', "Thermo Fisher"],
  ['ABT', "Abbott Labs"],
  ['DHR', "Danaher"],
  ['BMY', "Bristol-Myers"],
  ['AMGN', "Amgen"],
  ['GILD', "Gilead"],
  ['REGN', "Regeneron"],
  ['VRTX', "Vertex"],
  ['ISRG', "Intuitive Surgical"],
  ['BSX', "Boston Scientific"],
  ['SYK', "Stryker"],
  ['ZBH', "Zimmer Biomet"],
  ['DXCM', "DexCom"],
  ['VEEV', "Veeva Systems"],
  ['ILMN', "Illumina"],
  ['CI', "Cigna"],
  ['CVS', "CVS Health"],
  ['HCA', "HCA Healthcare"],
  ['HD', "Home Depot"],
  ['COST', "Costco"],
  ['WMT', "Walmart"],
  ['TGT', "Target"],
  ['TJX', "TJ Maxx"],
  ['ROST', "Ross Stores"],
  ['NKE', "Nike"],
  ['SBUX', "Starbucks"],
  ['CMG', "Chipotle"],
  ['YUM', "Yum! Brands"],
  ['DASH', "DoorDash"],
  ['KO', "Coca-Cola"],
  ['PEP', "PepsiCo"],
  ['MNST', "Monster Beverage"],
  ['PG', "Procter & Gamble"],
  ['CL', "Colgate"],
  ['KMB', "Kimberly-Clark"],
  ['DIS', "Disney"],
  ['NCLH', "Norwegian Cruise"],
  ['RCL', "Royal Caribbean"],
  ['MAR', "Marriott"],
  ['HLT', "Hilton"],
  ['BKNG', "Booking"],
  ['ABNB', "Airbnb"],
  ['LULU', "Lululemon"],
  ['ULTA', "Ulta Beauty"],
  ['ELF', "e.l.f. Beauty"],
  ['ETSY', "Etsy"],
  ['CHWY', "Chewy"],
  ['W', "Wayfair"],
  ['XOM', "ExxonMobil"],
  ['CVX', "Chevron"],
  ['COP', "ConocoPhillips"],
  ['SLB', "Schlumberger"],
  ['EOG', "EOG Resources"],
  ['PXD', "Pioneer Natural"],
  ['MPC', "Marathon Petroleum"],
  ['VLO', "Valero"],
  ['PSX', "Phillips 66"],
  ['OXY', "Occidental"],
  ['FANG', "Diamondback"],
  ['CAT', "Caterpillar"],
  ['BA', "Boeing"],
  ['GE', "GE Aerospace"],
  ['HON', "Honeywell"],
  ['DE', "John Deere"],
  ['UPS', "UPS"],
  ['FDX', "FedEx"],
  ['RTX', "RTX"],
  ['LMT', "Lockheed Martin"],
  ['NOC', "Northrop Grumman"],
  ['GD', "General Dynamics"],
  ['EMR', "Emerson"],
  ['ITW', "Illinois Tool Works"],
  ['PH', "Parker Hannifin"],
  ['MMM', "3M"],
  ['WM', "Waste Management"],
  ['RSG', "Republic Services"],
  ['F', "Ford"],
  ['GM', "General Motors"],
  ['RIVN', "Rivian"],
  ['NIO', "NIO"],
  ['LCID', "Lucid"],
  ['LI', "Li Auto"],
  ['XPEV', "XPeng"],
  ['SNAP', "Snap"],
  ['PINS', "Pinterest"],
  ['UBER', "Uber"],
  ['LYFT', "Lyft"],
  ['RBLX', "Roblox"],
  ['U', "Unity"],
  ['DKNG', "DraftKings"],
  ['MTCH', "Match Group"],
  ['SHOP', "Shopify"],
  ['PLTR', "Palantir"],
  ['CVNA', "Carvana"],
  ['HIMS', "Hims & Hers"],
  ['CAVA', "CAVA Group"],
  ['DUOL', "Duolingo"],
  ['TOST', "Toast"],
  ['ONON', "On Holding"],
  ['BROS', "Dutch Bros"],
  ['MSTR', "MicroStrategy"],
  ['MARA', "Marathon Digital"],
  ['RIOT', "Riot Platforms"],
  ['CLSK', "CleanSpark"],
  ['HUT', "Hut 8"],
  ['AMT', "American Tower"],
  ['PLD', "Prologis"],
  ['CCI', "Crown Castle"],
  ['EQIX', "Equinix"],
  ['SPG', "Simon Property"],
  ['O', "Realty Income"],
  ['T', "AT&T"],
  ['VZ', "Verizon"],
  ['TMUS', "T-Mobile"],
  ['CMCSA', "Comcast"],
  ['WBD', "Warner Bros"],
  ['PARA', "Paramount"],
  ['FOX', "Fox"],
  ['NEM', "Newmont Mining"],
  ['GOLD', "Barrick Gold"],
  ['FCX', "Freeport-McMoRan"],
  ['NUE', "Nucor"],
  ['STLD', "Steel Dynamics"],
  ['CLF', "Cleveland-Cliffs"],
  ['APD', "Air Products"],
  ['ECL', "Ecolab"],
  ['SHW', "Sherwin-Williams"],
  ['NEE', "NextEra Energy"],
  ['SO', "Southern Company"],
  ['DUK', "Duke Energy"],
  ['D', "Dominion Energy"],
  ['AEP', "American Electric"],
  ['XEL', "Xcel Energy"],
  ['LHX', "L3Harris"],
  ['AXON', "Axon Enterprise"],
  ['RKLB', "Rocket Lab"],
  ['BIIB', "Biogen"],
  ['CELH', "Celsius"],
  ['MRNA', "Moderna"],
  ['SPY', "S&P 500 ETF"],
  ['QQQ', "Nasdaq 100 ETF"],
  ['IWM', "Russell 2000 ETF"],
  ['DIA', "Dow Jones ETF"],
  ['ARKK', "ARK Innovation"],
  ['XLF', "Financial ETF"],
  ['XLE', "Energy ETF"],
  ['SOXX', "Semiconductor ETF"],
  ['XLK', "Tech ETF"],
  ['XLV', "Healthcare ETF"],
  ['XLI', "Industrial ETF"],
  ['GLD', "Gold ETF"],
  ['SLV', "Silver ETF"],
  ['TLT', "20yr Treasury ETF"],
  ['VIX', "Volatility Index"],
]

/** Best matches for a query: exact symbol, then symbol prefix, then name. */
export function searchTickers(query: string, limit = 7): [string, string][] {
  const q = query.trim().toUpperCase()
  if (!q) return []
  const exact: [string, string][] = []
  const prefix: [string, string][] = []
  const name: [string, string][] = []
  for (const row of TICKERS) {
    const [t, n] = row
    if (t === q) exact.push(row)
    else if (t.startsWith(q)) prefix.push(row)
    else if (q.length >= 2 && n.toUpperCase().includes(q)) name.push(row)
  }
  return [...exact, ...prefix, ...name].slice(0, limit)
}
